export const GameName = {
  DIGITAL_SPAN: "DIGITAL_SPAN",
  CARD_MATCH: "CARD_MATCH",
  SEQUENCE_RECALL: "SEQUENCE_RECALL",
  VISUAL_SEARCH: "VISUAL_SEARCH",
  STROOP_TEST: "STROOP_TEST",
  REACTION_TIME: "REACTION_TIME",
  GO_NO_GO: "GO_NO_GO",
  CHOICE_REACTION_TIME: "CHOICE_REACTION_TIME",
  PATTERN_RECOGNITION: "PATTERN_RECOGNITION",
  ARITHMETIC_PATTERN_RECOGNITION: "ARITHMETIC_PATTERN_RECOGNITION",
} as const;

export type GameName = (typeof GameName)[keyof typeof GameName];
